### PR TITLE
Replace subgraph endpoints

### PR DESCRIPTION
**Pull request by JO-OLADEJI**
I replaced the subgraph endpoints with what's currently documented on Aave's GitHub. On the deployment, a new `.env` variable: `REACT_APP_SUBGRAPH_KEY` will need to be added because TheGraph now uses api-keys for the querying of subgraphs.

### CODE REVIEW

**Comment by JO-OLADEJI** [comment]
Heyyy @Wilson-Wu1 👋
Please help review and merge. Thank you!

**Comment by Wilson-Wu1** [comment]
Hey @JO-OLADEJI, thank you so much for fixing the issue! I will look into the changes and test this week.

**Comment by Wilson-Wu1** [comment]
@JO-OLADEJI PR merged and deployed to prod! Thank you for your efforts 👍

**Comment by JO-OLADEJI** [comment]
Glad I could help out. I use the tool quite often!

**Pull request merged**
